### PR TITLE
[5.1] Fixes #165

### LINKED ISSUE #165: Making Seeder fails
```
$ php artisan make:seeder LinksTableSeeder
PHP Fatal error:  Call to undefined method Laravel\Lumen\Application::getNamespace() in /{path_to_laravel_project}/vendor/illuminate/console/GeneratorCommand.php on line 151

Fatal error: Call to undefined method Laravel\Lumen\Application::getNamespace() in /{path_to_laravel_project}/vendor/illuminate/console/GeneratorCommand.php on line 151
```

The `getNamespace()` method exists in the full-fledged Laravel framework, but not in Lumen. Bug?

### PR DESCRIPTION
**Pull request by Arrilot**
Closes #165

We can hardcode the namespace because there is no `app:name` command in Lumen, right?

### CODE REVIEW

**Comment by lukasgeiter** [comment]
Just because there's no `app:name` command doesn't mean you can't change the default app namespace.

**Comment by GrahamCampbell** [comment]
Yeh, this looks wrong to me.

**Comment by Arrilot** [comment]
Okay, makes sense.

Let's copy some Laravel stuff then and call it a day.

File: src/Application.php [hunk 1]
```diff
@@ -1538,6 +1556,32 @@ public function getRoutes()
     }
 
     /**
+     * Get the application namespace.
+     *
+     * @return string
+     *
+     * @throws \RuntimeException
+     */
+    public function getNamespace()
```
Comment (GrahamCampbell) [inline src/Application.php]: Why do we even need this method. :-1: for adding it.

Comment (Arrilot) [inline src/Application.php]: As you can see in the issue some Illuminate components that Lumen uses require it .

Comment (GrahamCampbell) [inline src/Application.php]: I don't think we should support those parts.

Comment (GrahamCampbell) [inline src/Application.php]: Infact, we don't...
